server:
  port: 8080

spring:
  application:
    name: sewa-mobil-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sewa_mobil_db}
    username: ${SPRING_DATASOURCE_USERNAME:db_sewa}
    password: ${SPRING_DATASOURCE_PASSWORD:Pasword123!}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173,http://localhost:8080,http://127.0.0.1:8080}
